// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using baitap_EF_CodeFirst_NhanVien.data_access;

#nullable disable

namespace baitap_EF_CodeFirst_NhanVien.data_access.migration
{
    [DbContext(typeof(QuanLyNhanVienCodeFirstDbContext))]
    [Migration("20240423104344_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.CongTy", b =>
                {
                    b.Property<string>("MaCongTy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCongTy");

                    b.ToTable("CongTy");
                });

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongBanMaPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("MaNV");

                    b.HasIndex("PhongBanMaPB");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CongTyMaCongTy")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCongTy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPB");

                    b.HasIndex("CongTyMaCongTy");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.NhanVien", b =>
                {
                    b.HasOne("baitap_EF_CodeFirst_NhanVien.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("PhongBanMaPB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.PhongBan", b =>
                {
                    b.HasOne("baitap_EF_CodeFirst_NhanVien.Models.CongTy", "CongTy")
                        .WithMany("PhongBans")
                        .HasForeignKey("CongTyMaCongTy");

                    b.Navigation("CongTy");
                });

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.CongTy", b =>
                {
                    b.Navigation("PhongBans");
                });

            modelBuilder.Entity("baitap_EF_CodeFirst_NhanVien.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
